### ISSUE TITLE
Peculiar ipynb link after requesting rmd transfer

### ISSUE THREAD

**Issue by vjcitn** [Bioconductor/AnVILPublish#12]
Notice the hyperlink towards the bottom, to an ipynb file ... intended?

request was
```
as_workspace("BiocHail", "landmarkanvil2", update=TRUE, use_readme=TRUE, type="rmd")
```
AnVILPublish 1.9.0

![apub](https://user-images.githubusercontent.com/4624066/206924125-2656562a-15f9-4552-985b-2fa98a7ca3ef.png)

**Comment by mtmorgan** [comment]
Yes, I see why this occurs; it seems like it has always been like this (and wrong). I guess that the Rmd notebooks show up under the ANALYSES tab and in RStudio...?

**Comment by vjcitn** [comment]
hmph ... i went to check and it logged me out.  yes they show up in the analyses tab, but i wonder if they are pushed (or received) with suffix .ipynb and then are renamed?  because i am pretty sure i saw them first as ipynb.

**Comment by mtmorgan** [comment]
AnVILPublish doesn't change the extension under ANALYSES; it copies the Rmd file. Things might go awry if there are also .ipynb versions of the notebooks in the vignettes/ directory of the source package?

**Comment by mtmorgan** [comment]
https://github.com/Bioconductor/AnVILPublish/tree/R-3-16-link-Rmd-from-dashboard (`BiocManager::install("Bioconductor/AnVILPublish", ref = "R-3-16-link-Rmd-from-dashboard")`) starts to address this.

The Rmd and / or ipynb are now linked correctly to the dashboard.

It seems that clicking on these links mostly fails (I believe the 'Preview' feature of Terra relies on an out-of-date R installation without packages such as BiocStyle that might be mentioned in the YAML, and also for other less transparent reasons -- I'll work on getting these to the attention of the Terra team -- `quarto render <file.Rmd> --to gfm --no-execute` should be good enough for a preview and does not require a complicated R installation).

**Comment by vjcitn** [comment]
type = "rmd" still produces .ipynb link on the dashboard (but I did not try the branch mentioned above).
Should the branch be merged?

**Comment by mtmorgan** [comment]
Please try the branch. Any comments on the restrictions? Does preview still fail?
