### ISSUE TITLE
configuring notedown

### ISSUE THREAD

**Issue by vjcitn** [Bioconductor/AnVILPublish#13]
Given the importance of notedown to the conversion process, should the discipline at https://cran.r-project.org/web/packages/reticulate/vignettes/python_dependencies.html under "Using Config/reticulate" be followed?  At the bottom of the page a method of pinning the version is described.

**Comment by mtmorgan** [comment]
If quarto is available, then it will be used in preference to notedown. notedown is not well-maintained (last commit in 2017) so probably a better path is to explicitly require quarto and remove notedown.

I'm not sure whether the AnVIL docker image contains quarto; I think it does @almahmoud ?

**Comment by vjcitn** [comment]
ok, somehow notedown was prominent in doc, i will try to give more details if necessary.
